### ISSUE TITLE
`/topics/faq.md` has outdated info

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#103]
In review for publishing (#91), I found the following issues:

> 64-bit systems will use considerably more memory than 32-bit systems to store the same keys, especially if the keys and values are small. This is because pointers take 8 bytes in 64-bit systems. But of course the advantage is that you can have a lot of memory in 64-bit systems, so in order to run large Valkey servers a 64-bit system is more or less required. The alternative is sharding.

Discussing 32 bit vs 64 bit seems like irrelevant information in 2024.

> As of version 4.0, Valkey has started implementing threaded actions. For now this is limited to deleting objects in the background and blocking commands implemented via Valkey modules. For subsequent releases, the plan is to make Valkey more and more threaded.

Remove anything before 6.0

> Why does my replica have a different number of keys its master instance?

Update to primary/replica terminology.

**Comment by zuiderkwast** [comment]
Fixing these issues.

Serious problem with "How can Valkey use multiple CPUs or cores?" so I decided to open #196. I'm going to replace the answer here with a short sentence about I/O threading, just to have something.
