### ISSUE TITLE
`/topics/functions-intro.md` has bad formatting, improper framing

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#104]
In pre-publishing review (#91) I found the following issues on `functions-intro.md`

> !KEYS and ARGV Lua APIs

Using the odd bang formatting which is invalid Valkey syntax.

> Redis OSS v7.0 introduces Valkey Functions

Redis didn't introduce Valkey Functions :) 

> There are plans to support additional engines in the future.

Is this still true? It's probably best to remove forward looking statements in the documentation if there isn't some way to track it with an issue or roadmap item.

**Comment by madolson** [comment]
> Is this still true? It's probably best to remove forward looking statements in the documentation if there isn't some way to track it with an issue or roadmap item.

No, this was Redis ltd. wording because they wanted to add javascript support to the main engine. We should drop this.

**Comment by zuiderkwast** [comment]
Gah, this page is written like a promotion text for Functions. I feel like dropping most of it but I don't want to spend time on it. It's hard to resist though.

> > !KEYS and ARGV Lua APIs
> 
> Using the odd bang formatting which is invalid Valkey syntax.

This was used quite consistently throughout the docs (and much of it remains), even in the JSON files about history of command parameters, to prevent an all-caps word from being auto-linked too the command with the same name. Here KEYS doesn't refer to the KEYS command and shouldn't be linked to it.

Do we ever want to auto-link an all-caps words to a command with that name? If not, then we can delete these bangs throughout the docs. I've kept them so far and worked around them in the man page generation, but I don't like these non-markdown marks. I'd be happy to drop them. We should make a separate effort for all pages (grep + review) and another one for the JSON files in the code repo.

>> There are plans to support additional engines in the future.
>
> Is this still true? It's probably best to remove forward looking statements in the documentation if there isn't some way to track it with an issue or roadmap item.

Hm... We do have some ongoing work to make it possible. I'll change it to "may be possible" and adjust the rest of this text. Some other wordings in this text refers to "engines", that they potentially can exist.
