### ISSUE TITLE
`/topics/get-started.md` is sparse

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#105]
In pre-publishing review (#91), I noticed the `get-started` docs page is correct but should be expanded.

**Comment by zuiderkwast** [comment]
It links to quickstart.md, which is the real getting started page, before Redis Ltd added another layer before this, to add links to their enterprise get-started pages.

IMO get-started.md can be replaced by quickstart.md.

It's very hard to know what you want to add from a phrase like "should be expanded".

**Comment by zuiderkwast** [comment]
I'm deleting this silly page. We have `quickstart.md` for this.

For topics like pubsub and other stuff, we have other pages with introductions and examples.
