### ISSUE TITLE
`/topics/internals-eventlib.md` should be removed or not published

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#109]
In pre-publishing review (#91), I've come to the conclusion that `internals-eventlib.md` should be removed from this repo or, at very least, not published on valkey.io.

1. This file has a disclaimer about it's age and context, but it still changes the name to valkey throughout. This is confusing.
2. It refers to files as `redis.c` and structures that are named with redis*. The value in this file is diminished totally unless you know the mapping of how Redis and Valkey relates.
3. Valkey has evolved considerably from the very early versions of Redis in 2010. For computing generally, the constraints and considerations in 2010 are likely different than those in 2024.

I think the risk in this documentation confusing the reader is greater than the historical value it provides. Additionally, this information can still be found on the redis repos for those interested.

**Comment by madolson** [comment]
I would probably vote to just drop it. It is very old, and has changed significantly over the years.

**Comment by zuiderkwast** [comment]
We still have a custom event library. I found the historical context relevant just a few days ago, especially the mail thread on google groups.

This kind of descriptions belong in code comments though, at most. Yank!
