### ISSUE TITLE
`/topics/internals-vm.md` should be removed or not published

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#110]
In pre-publishing review (#91), I've come to the conclusion that `internals-vm.md` should be removed from this repo or, at very least, not published on valkey.io. This is a similar situation to #109 

1. It refers to something from Redis 2.6 and below as the `Valkey Virtual Memory`, which is confusing.
2. It comments on something as a 'Valkey Object' then in the source code as a 'redisObject'
3. There is references to an old and new Valkey Object structure but these are both structures that only ever existed in Redis.
4. It talks about vm-page sizes in valkey.conf, but they've never existed in valkey.conf

(probably more)

Overall, I think the risk in this documentation confusing the reader is greater than the historical value it provides. Additionally, this information can still be found on the redis repos for those interested.

**Comment by madolson** [comment]
We should just delete it.
