### ISSUE TITLE
`/topics/introduction.md` needs updated language about 'support'

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#111]
In pre-publishing review (#91), I found the following passage on `/topics/introduction.md`

> Valkey is written in ANSI C and works on most POSIX systems like Linux, *BSD, and Mac OS X, without external dependencies. Linux and OS X are the two operating systems where Valkey is developed and tested the most, and we recommend using Linux for deployment. Valkey may work in Solaris-derived systems like SmartOS, but support is best effort. There is no official support for Windows builds.

This has a few issues:
- `Mac OS X` / `OS X` -> `MacOS`
- `Valkey may work in Solaris-derived systems like SmartOS` to my knowledge Valkey has been tested on anything Solaris derived
- ` There is no official support for Windows builds.` -> Maybe talk about WSL?

**Comment by zuiderkwast** [comment]
We receive Solaris related contributions from time to time, so I believe some people run this. Illumos is a more recent variant I believe. We don't have any CI for it though, so I believe "may work" is appropriate, for now (until someone adds a CI job for it). Solaris is POSIX so it *should work*.

Regarding Windows, I wouldn't want to dive into that swamp. If we do mention WSL, should we go into MinGW and Cygwin too? I believe windows users can figure this out, or use a VM, if they persist running a non-Posix system.

The name of MacOS is the one thing that's clearly worth fixed here IMO.
