### ISSUE TITLE
`/topics/latency.md` is out dated information an references non existent things

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#113]
In pre-publishing review (#91), the following issues were discovered

> This is an example run under Linux 3.11.0 running on an entry level server.

Linux 3.11.0 is from 2013-ish and is long out of support. It would be good to modernize this section with a more common kernel in 2024.

> new types of EC2 HVM based instances are much better with fork times

I don't think these would be considered new. Additionally there is an entire list of machines and their performance; I think most of these machines are from about a decade ago and their performance provides little value in 2024.

> Valkey Google Group

(two mentions). No such google group exists.

**Comment by zuiderkwast** [comment]
> > This is an example run under Linux 3.11.0 running on an entry level server.
> 
> Linux 3.11.0 is from 2013-ish and is long out of support. It would be good to modernize this section with a more common kernel in 2024.

I tried it on my laptop and it's not better than the 2013 server. We'd need to try it on a modern server to get some good numbers. (I don't have one at hand ATM.)

The numbers here are actually irrelevant. It's the explanation how to do this that matters. I'm adding a parenthesis that this is old, but it illustrates how to measure this.



> > new types of EC2 HVM based instances are much better with fork times
> 
> I don't think these would be considered new. Additionally there is an entire list of machines and their performance; I think most of these machines are from about a decade ago and their performance provides little value in 2024.
> 

Deleting this list of machines. Rewriting the section.



> > Valkey Google Group
> 
> (two mentions). No such google group exists.

Changing to open an issue on GitHub.
