### ISSUE TITLE
`/topics/protocol.md` needs work: naming, links, and malformed HTML

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#127]
In pre-publishing review (#91), I found several issues on `/topics/protocol.md`

"Valkey serialization protocol specification" title

Drop "Valkey"

> While the protocol was designed specifically for Valkey, you can use it for other client-server software projects.

It wasn't designed specifically for Valkey. Refactor.

> Support for the first version of the RESP protocol was introduced in Redis OSS 1.2. Using RESP with Redis OSS 1.2 was optional and had mainly served the purpose of working the kinks out of the protocol.

This isn't relevant for Valkey/2024.

> The [RESP3 Push type](#).

Links to a hash that doesn't exist.

> `<a name="boolean-reply">` 

The `a` tag isn't closed causing the entire section to become an unclickable link.

![Screenshot 2024-05-30 at 1 21 46 PM](https://github.com/valkey-io/valkey-doc/assets/1152927/a4bae409-3636-4dd2-8700-15e1ddbe26d4)

> `<a name="verbatim-string-reply">`

The `a` tag isn't closed causing the entire first line to become an unclickable link

![Screenshot 2024-05-30 at 1 24 46 PM](https://github.com/valkey-io/valkey-doc/assets/1152927/e6fe0e45-f2a1-42cb-a195-dd327bf75102)

**Comment by zuiderkwast** [comment]
> Drop "Valkey"
> "was designed specifically for Valkey"

I'll drop, refactor, etc. as appropriate.

> > Support for the first version of the RESP protocol was introduced in Redis OSS 1.2. Using RESP with Redis OSS 1.2 was optional and had mainly served the purpose of working the kinks out of the protocol.
> 
> This isn't relevant for Valkey/2024.

I'll refactor/minify. (It's of some historical interest.)

> `<a name="boolean-reply">`

I'll delete all these manually added anchors and update all links to these sections, from this and other pages, to the correct ones.

**Comment by zuiderkwast** [comment]
@stockholmux This page is still not visible on the website. Does it still have issues?

**Comment by stockholmux** [comment]
@zuiderkwast Indeed there is a problem. The content looks generally fine but there is something weird going on with the file, when I remove the file from the publishing hold it renders like this:

![Screenshot 2024-12-09 at 8 38 07 AM](https://github.com/user-attachments/assets/02fe5f45-64df-4cb1-8f44-be0d63a8c4aa)

The weird single bullet seems to be related to some sort of errant character somewhere in the frontmatter section. It also blows up my markdown linter in vscode (note the related errors shown while mousing over the errors don't seem to be related to the issue):

<img width="517" alt="Screenshot 2024-12-09 at 8 40 10 AM" src="https://github.com/user-attachments/assets/99caf150-dabf-4bfb-94ea-44b7cb6b6853">

When I manually remove the frontmatter in the source file and re-write it there it renders fine:

![Screenshot 2024-12-09 at 8 42 36 AM](https://github.com/user-attachments/assets/ac08bb29-25ad-4ea0-8527-4e49a426d28a)

It's quite weird really; none of the other topics have this problem. I don't see a tab character anywhere but that would be my first guess; the fix should be easy - just remove the existing frontmatter and re-enter it cleanly.

**Comment by stockholmux** [comment]
Gosh! I didn't notice the extra dash but that'll do it!
