### ISSUE TITLE
`/topics/pubsub.md` has very old, broken example.

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#128]
In pre-publishing review (#91), I noticed that there is a linked example that probably does not work.

> Programming example
Pieter Noordhuis provided a great example using EventMachine and Valkey to create [a multi user high performance web chat](https://gist.github.com/pietern/348262).

On the linked gist it says:

```
# Update 7 Oct 2010:
# - This example does *not* appear to work with Chrome >=6.0. Apparently,
#   the WebSocket protocol implementation in the cramp gem does not work
#   well with Chrome's (newer) WebSocket implementation.
```

Note, the current version of Chrome is 125.x

**Comment by zuiderkwast** [comment]
Deleting the "programming example".
