### ISSUE TITLE
`/topics/rdd.md` needs valkey/redis to be clarified

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#129]
In pre-publishing review (#91), I found a couple of confusing uses of naming. I do think this historical document could provide useful context unlike several other similar documents, however as it is, it's a bit confusing.

> Valkey Design Draft 2 -- RDB version 7 info fields

Since this document is in context of Redis design decisions, we should probably remove Valkey from the heading

> The Valkey RDB format lacks a simple way to add info fields to an RDB file without causing a backward compatibility issue even if the added meta data is not required in order to load data from the RDB file.

I would drop `Valkey` here as it was written by Salvatore.

**Comment by zuiderkwast** [comment]
I'd say let's delete this page. It doesn't belong in documentation. Besides, it's very outdated. Many changes have been done to the RDB file format since then.
