### ISSUE TITLE
`/topics/replication.md` has a few naming/terminology issues

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#130]
In pre-publishing review (#91), I found the following issue on `/topics/replication.md`

> Since Redis OSS 4.0, all the sub-replicas will receive exactly the same replication stream from the master.

and

> Before version 4.0, writable replicas were incapable of expiring keys with a time to live set.

We can remove the old versions.

We also need to update the language to use 'primary'.

**Comment by zuiderkwast** [comment]
We have just taken the decision to change master to primary. Until now, "master" us used consistently in the docs and in logging, error message, etc. from Valkey. I think we should do this change as a separate effort.

**Comment by zuiderkwast** [comment]
Removing the references to 4.0. For "master", refer to #148
