### ISSUE TITLE
`/topics/sentinel-clients.md` has outdated references and terminology, mentions non-existent google group

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#132]
In pre-publishing review (#91) I noticed several issues with `/topics/sentinel-clients.md`

> If the ROLE commands is not available (it was introduced in Redis OSS 2.8.12), a client may resort to the INFO replication command parsing the role: field of the output.

and

> Starting with Redis OSS 2.8.12

Remove reference to 2.8.12

> For additional information or to discuss specific aspects of this guidelines, please drop a message to the [Valkey Google Group](https://groups.google.com/group/redis-db).

There isn't a Valkey Google group, so this should be deleted.

Finally, there are 44 references that need to be updated to `primary`

**Comment by zuiderkwast** [comment]
Addressing this, except "master" which I'm leaving for #148
