### ISSUE TITLE
`/topics/sentinel.md` needs updated terminology, has differing hash links, refers to the wrong project

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#133]
In pre-publishing review (#91), I found the following issues on `/topics/sentinel.md`

> This is a Sentinel event, and you can receive this kind of events via Pub/Sub if you SUBSCRIBE to the event name as specified later in [Pub/Sub Messages section](#pubsub-messages).

and 

> Lastly, Sentinel also supports the `SUBSCRIBE`, `UNSUBSCRIBE`, `PSUBSCRIBE` and `PUNSUBSCRIBE` commands. Refer to the [_Pub/Sub Messages_ section](#pubsub-messages) for more details.

Both link to '#pubsub-messages', the website creates hash ID of `#pub-sub-messages` on the heading "Pub/Sub messages" whilst github creates '#pubsub-messages'. It probably needs to add a manual anchor for these links to work on both platforms.

> AUTH (>= 5.0.1) Authenticate a client connection. For more information refer to the AUTH command 

Drop '>= 5.0.1' since it's before 6.0.0

> Starting with Valkey OSS 6.2, Sentinel also allows getting and setting global configuration parameters which were only supported in the configuration file prior to that.

and 

> Valkey OSS 6

and

> Valkey OSS 5.0.1

and

> Valkey OSS 5

Valkey starts at 7.2.5, so these refer to the wrong project.

>  Unfortunately in this command the word slave is part of the protocol, so we'll be able to remove such occurrences only when this API will be naturally deprecated.

Is there still a plan to naturally deprecated this API? I know the current stance is something like 'never break an API', perhaps this language needs to be tweaked.

Finally, this needs extensive updates to terminology: 200+ cases that need to be updated to 'primary'.

**Comment by zuiderkwast** [comment]
I'm simply changing "Pub/Sub messages" to "Pubsub messages" to make the link `#pubsub-messages` work consistently.

Double-plus-rebranding (Valkey OSS) cleaned up. :)

Old references removed. Also removing more occurrences of `>= 3.2`, `>= 5.0`.

Not touching "master" for now. Let's do it in #148.
