### ISSUE TITLE
`/topics/signals.md` mentions old version of Redis and needs updated terminology

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#134]
In pre-publishing review (#91), I found the following issues on `/topics/signals.md`

> Since Redis OSS 2.8, a fast memory test is performed as a first check of the reliability of the crashing system.

Drop references to old versions

Additionally, 5 references need to be updated to primary.

**Comment by zuiderkwast** [comment]
I'm handling this. I opened #148 to track changing master to primary throughout the docs.
