### ISSUE TITLE
`/topics/transactions.md` has references to the previous project

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#137]
In pre-publishing review (#91) I found that `/topics/transactions.md` has a passage that wasn't re-branded

> Something else to consider for transaction like operations in redis are [redis scripts](#117 

These should both be changed from 'redis' to 'Valkey'

**Comment by zuiderkwast** [comment]
Good findings. I'm addressing these.

Additionally:

* Deleting a reference to "Redis OSS versions before 6.0.9" and a link to an issue in the redis repo. This version will soon be unmaintained.
* Rewriting a paragraph about new functionality in "version 5".
