### ISSUE TITLE
Change terminology "master" to "primary"

### ISSUE THREAD

**Issue by zuiderkwast** [valkey-io/valkey-doc#148]
Many pages to update.

Note that Redis official terminology is still master/replica. We're right now adding some aliases to allow the use of "primary" as an alias of "master" in various command parameters, etc., but this work is just being started.

The pages with very many occurrences:

* `topics/replication.md`
* `topics/sentinel.md`

The *note about the word slave* found in some pages needs to be updated to instead mention that the master/slave terminology is replaced by primary/replica.

**Comment by nastena1606** [comment]
I'll take this one
