### ISSUE TITLE
Update references from Redis to Valkey

### ISSUE THREAD

**Issue by madolson** [valkey-io/valkey-doc#18]
We need help updating the documentation to update all references of Redis to Valkey outside of the command references (which was previously completed in https://github.com/valkey-io/valkey-doc/pull/4). When updating the documentation, watch out for the following:
1. Only update independent references to Redis. Links to "redis.io" can usually be updated to "valkey.io" because the pages are organized in the same way (the contents of this doc repo). Don't update parts of other URLs or references to external websites. Feel free to delete references to Redis inc. products like RedisJSON as appropriate.
2. Generally keep the capitalization.  "Redis" -> "Valkey" and "redis" -> "valkey". This works for almost all usage, for example `redis-cli` becomes `valkey-cli`. Some usages of lowercase "redis" need to be handled specially though:
   * The `redis` object in Lua scripts is replaced by `server`. Examples:
     ```diff
     -EVAL_RO "return redis.call('GET', KEYS[1])" 1 mykey
     +EVAL_RO "return server.call('GET', KEYS[1])" 1 mykey
     ```
     ```diff
     -FUNCTION LOAD "#!lua name=mylib \n redis.register_function('myfunc', function(keys, args) return args[1] end)"
     +FUNCTION LOAD "#!lua name=mylib \n server.register_function('myfunc', function(keys, args) return args[1] end)"
     ```
   * Examples where "redis" is part of the valkey-cli prompt are just wrong. The real prompt is just the host and port.
     ```diff
     -redis 127.0.0.1:6379> scan 0
     +127.0.0.1:6379> scan 0
     ```

4. Skip the names of clients and tools. "StackExchange.Redis" is obviously the name of a client. It's best to skip the whole directories `clients/`, `modules/` and `tools/` when doing the bulk of this work and we'll handle them separately. (We need to investigate, discuss and decide what to do with them.)
5. Explicit references to old version of Redis are handled in either of these ways, depending on the context and usefulness of the information:
   * If it's references to Redis 1-5 (really old), they are simply deleted, but sometimes the sentences need to be rewritten to make sense. Examples:
      * ```diff
        -Starting with Redis 3.2, it is possible to
        +It is possible to
        ```
      * ```diff
        -Firstly, and ever since Redis 2.6.0, the `EVAL` command enables running server-side scripts.
        +Firstly, the `EVAL` command enables running server-side scripts.
        ```        
      * Delete the whole section or note if it's only valid for the really old versions.
        ```diff
        -**Note for Redis < 2.6.5:** Prior to Redis 2.6.5 clients needed to detect errors occurring prior to `EXEC` by checking
        -the return value of the queued command: if the command replies with QUEUED it was
        ```
      * ```diff
        -Redis 2.6 introduces the *Redis Software Watchdog* that is a debugging tool
        +Valkey comes with a *Software Watchdog* that is a debugging tool
        ```
      * ```diff
        -In version Redis 2.8, a new feature was introduced that allows
        -getting ranges lexicographically, assuming elements in a sorted set are all
        +It is possible to
        +get ranges lexicographically, assuming elements in a sorted set are all
        ```
   * If it's related to the upgrade path or compatibility, include the reference to the old Redis version, but refer to Redis using the term "Redis OSS", like "Redis OSS 6.0". This is according to [Redis Trademark Policy](https://redis.io/legal/trademark-policy/).
     * ```diff
       -Note that before Redis 7.2.0, **seen-time** used to denote the last successful interaction.
       +Note that before Redis OSS 7.2.0, **seen-time** used to denote the last successful interaction.
       ```
   * When reference to 4.0 and newer are deleted, post them here so we can pull them into a compatibility page for future reference.
6. Don't edit `docs/reference/modules/modules-api-ref.md`. It's generated from `module.c` in the code repo. (We can do that in a separate PR.)
7. Don't edit `commands.json`. It's generated from the main repo. (We can do that in a separate PR.)
8. Some pages are completely irrelevant. Don't waste time to rewrite the text about things which is not relevant to Valkey. Maybe we'll delete some of these pages later (not in the same PR).

**Comment by stockholmux** [comment]
I noticed on #25 and #26 that there are some files that are _only_ metadata (just yaml between two sets of `---`). 

It's a good exercise to rid Redis from these documents, but we shouldn't sweat the details on the metadata (unless @zuiderkwast you use this metadata on man pages?).

**Comment by zuiderkwast** [comment]
Those are some kind titles for the menus or categories?

I don't mind you delete them, though they could be considered content too.

The more important part to keep are the aliases listed in many files, for creating redirects. There are manu URLs in various places using older URLs like /topics/

**Comment by stockholmux** [comment]
> Those are some kind titles for the menus or categories?
> 
> I don't mind you delete them, though they could be considered content too.

More/less. It's kind of a messy mix of titles and becoming menu entries. The result is a really tight coupling: you may not want the page title (stuff at the top of the screen) to be the same as what appears in a menu or hierarchy.

> The more important part to keep are the aliases listed in many files, for creating redirects. There are manu URLs in various places using older URLs like /topics/

It's an interesting question if we should try to maintain redirects from another site. Redirects are IMHO a bandaid. I'd rather clean up misdirected links as they are moved to publication. There's no legacy SEO or real external links to valkey.io at the moment.

If we have to maintain redirects, I'd rather have a centralized location rather than it being spread over dozens or hundreds of files. 

(I'm not a zealot on these convictions though)

**Comment by zuiderkwast** [comment]
Ok, i trust you with changing all this. I think you have good judgment about coupling. Just make sure to grep for `valkey.io/` in all our repos and fix the links. :)

**Comment by zuiderkwast** [comment]
actually even relative links within this doc repo.

**Comment by SoulPancake** [comment]
Can I also help out with this?

**Comment by zuiderkwast** [comment]
@SoulPancake yes! We just need to structure the work a little, so we don't step on each others toes. I'll try to limit the scope of this PR and clarify some details that has come up.

**Comment by zuiderkwast** [comment]
@SoulPancake I've added some details in the issue description above and reduced the scope bit. Do you think it's doable in one PR?

(We don't touch `clients/`, `tools/` and `modules/` for now.)

**Comment by SoulPancake** [comment]
Seems to be doable in a single PR 
or we can start out with one and then iteratively add to that if required
@zuiderkwast

**Comment by zuiderkwast** [comment]
Quick rebrand done for everything under docs/ and commands/.

What remains are the descriptions of clients, modules, tools, libraries. For these, we need to keep Redis when it's part of their names. The file structure also encodes their repository locations, so if it contains `github.com/redis/` we need to keep this part. It may not be strictly necessary to fix these descriptions before website launch.

**Comment by zuiderkwast** [comment]
I went over the clients, module, libraries and tools. Many of them have "Redis" in their names and they describe themselves as tools for Redis, which they are, so I think it's correct. It's not against any trademark rules to list Redis clients on any website AFAIK. We should make sure that we mention on our website that Redis is a trademark of Redis though.

There are very few occurrences left under topics/. I'll handle them right away.
