### ISSUE TITLE
Antirez blog forwards to redis, lacks valid cert, switch to wayback machine links

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#188]
The docs reference Salvatore's blog liberally for both historical context and technical information.

It's been a long term, known issue that the blog lacks a valid certificate and has a scary "Not Secure" warning and is only accessible via `http`, not `https`. 

I noticed recently that my browser (Chrome) tried to do a move to `https` when manually pasting an `http` antirez.com URL into the address bar; https forwards to the redis.io domain which resolves to the redis corporate page (and results in a broken link). It seems that Chrome will, for now, follow http _links_ in a page.

Indeed, `https` links on antirez.com are being 301 redirected to redis.io, as seen by `wget`:

```
$ wget https://antirez.com/news/133 --no-check-certificate
--2024-11-20 07:40:10--  https://antirez.com/news/133
Resolving antirez.com (antirez.com)... 178.62.37.191
Connecting to antirez.com (antirez.com)|178.62.37.191|:443... connected.
WARNING: cannot verify antirez.com's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
WARNING: no certificate subject alternative name matches
	requested host name ‘antirez.com’.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://redis.io/news/133 [following]
--2024-11-20 07:40:11--  https://redis.io/news/133
Resolving redis.io (redis.io)... 45.60.123.1, 45.60.129.1
Connecting to redis.io (redis.io)|45.60.123.1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-20 07:40:12 ERROR 404: Not Found.
```

I think it might be wise to move antirez.com links to wayback machine links.

E.g. http://antirez.com/news/133 -> https://web.archive.org/web/20241019222138/http://antirez.com/news/133

This resolves the current issue of `http` warnings in browsers and any potential forwarding shenanigans in the future.

**Comment by zuiderkwast** [comment]
Yes please, I would accept a PR.

**Comment by zuiderkwast** [comment]
It seems antirez now has a TLS certificate, so we can change the links to https.
