### ISSUE TITLE
Documentation of unreleased changes appears on https://valkey.io/commands/set/

### ISSUE THREAD

**Issue by gmbnomis** [valkey-io/valkey-doc#203]
Apparently, `valkey-io.github.io` uses the default branches of the `valkey` and `valkey-doc` repositories when rendering the web pages. This means that e.g. the `IFEQ`  option of the `SET` command is visible on [valkey.io](https://valkey.io/commands/set/) although that extension is not part of a released version yet.

I wasn't sure where to open this issue, I suppose it needs changes to both `valkey-doc` (branches?) and to `valkey-io.github.io`

**Comment by stockholmux** [comment]
@gmbnomis I believe that is intentional. There was a strong opposition to versioned docs, so the website and docs reflect the latest changes with a version history.

This also helps to cover those using the RC/prerelease version to know understand the newest features.

**Comment by gmbnomis** [comment]
I see. I am going to close this issue, then. Thank you for the clarification.
