### ISSUE TITLE
Malformed markdown in docs

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-doc#87]
The following files have malformed markdown that prevent SSGs from rendering the site.

- [admin.md](https://github.com/valkey-io/valkey-doc/blob/main/topics/admin.md?plain=1#L48)
- [cli.md](https://github.com/valkey-io/valkey-doc/blob/main/topics/cli.md?plain=1#L218)
- [eval-intro.md](https://github.com/valkey-io/valkey-doc/blob/main/topics/eval-intro.md?plain=1#L402)
- [programmability.md](https://github.com/valkey-io/valkey-doc/blob/main/topics/programmability.md?plain=1#L18)

These are all related to links with missing URLs. This causes Zola to stop the world with an error: `Error: Reason: Failed to render markdown filter: There is a link that is missing a URL.` It appears this is a regression introduced in #61 which just ate some URLs.

**Comment by zuiderkwast** [comment]
OK, thanks! I'll fix these and open a PR.

These links were previously pointing to files that were missing. I suspect they were broken already before we forked. (#61 checked that the files exist, but it wasn't supposed to be able to return empty links.)

I see that in admin.md, the link is supposed to be to quickstart.md, but this file was renamed and lost in history. Now, that content is in a file called data-store.md. Do you mind if I rename data-store.md back to its original name quickstart.md?

get-started.md is linking to get-started.md and not much more. It's a dummy page basically. (It used to link to some redis labs stuff but we deleted it.) Do you mind that I delete get-started.md?

The others are easy fixes:
* cli.md is supposed to link to mass-insertion.md
* topics/eval-intro.md is supposed to link to cli.md
* topics/programmability.md is supposed to link to data-types.md
